name: Bug report
description: Report an issue or bug with this library
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, and any additional context.
      placeholder: Describe what happened...
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Using the following...
        2. I was trying to do this...
        3. Then, I got this error...
    validations:
      required: true
  - type: textarea
    id: code-snippets
    attributes:
      label: Code snippets
      description: If applicable, add code snippets to help explain your problem.
      render: JavaScript
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Windows 11
    validations:
      required: true
  - type: input
    id: language-version
    attributes:
      label: Node version
      placeholder: Node v16.14.0
    validations:
      required: true
  - type: input
    id: lib-version
    attributes:
      label: Library version
      placeholder: '@udlearn/genpass v1.1.0'
    validations:
      required: true